#define HILL_SUBS_RIVER_MSG 3

#define HILL_SUBS_MNTN_MSG_MIN 3
#define HILL_SUBS_MNTN_MSG_MAX 4

#define HILL_SUBS_MNTN_SUBMSG_MIN 9
#define HILL_SUBS_MNTN_SUBMSG_MAX 15

#define HILL_SUBS_MNTN_OPTS_MIN 6
#define HILL_SUBS_MNTN_OPTS_MAX 7

#define HILL_SUBS_RIVER_OPTS_MIN 5
#define HILL_SUBS_RIVER_OPTS_MAX 7

void hill_subs_mntn();
void hill_subs_river();