import configparser
import time
import os

def spookPull():
    while True:
        try:
            file = open('plains.txt', 'r')
            lines = file.readlines()
            ee = lines[0]
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
            print(ee)
            time.sleep(0.25)
            os.system('cls||clear')
            time.sleep(0.5)
        except FileNotFoundError:
            return

def savePull():
    while True:
        try:
            config = configparser.ConfigParser() #Verify config files are found and valid
            config.read('save/config.ini')
            var1 = config.getint('ch1endflag', 'var1')
            print(var1)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config2.ini')
            var2 = config.getint('chaptflagger', 'var2')
            print(var2)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config3.ini')
            var3 = config.getint('toolflag', 'var3')
            print(var3)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config4.ini')
            var4 = config.getint('friendflag', 'var4')
            print(var4)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config5.ini')
            var5 = config.getint('reset', 'var5')
            print(var5)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config6.ini')
            var6 = config.getint('lizard', 'var6')
            print(var6)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config7.ini')
            var7 = config.getint('lizardext', 'var7')
            print(var7)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config8.ini')
            var8 = config.getint('okay', 'var8')
            print(var8)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config9.ini')
            var9 = config.getint('badend', 'var9')
            print(var9)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config10.ini')
            var10 = config.getint('badendext', 'var10')
            print(var10)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config11.ini')
            var11 = config.getint('splashskip', 'var11')
            print(var11)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config12.ini')
            var12 = config.getint('lizarddx', 'var12')
            print(var12)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config13.ini')
            var13 = config.getint('splashskip2', 'var13')
            print(var13)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config14.ini')
            var14 = config.getint('gameover', 'var14')
            print(var14)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config15.ini')
            var15 = config.getint('blade', 'var15')
            print(var15)
            time.sleep(0.04)
            config = configparser.ConfigParser() #Verify config files are found and valid
            config.read('save/config.ini')
            var1 = config.getint('ch1endflag', 'var1')
            print(var1)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config2.ini')
            var2 = config.getint('chaptflagger', 'var2')
            print(var2)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config3.ini')
            var3 = config.getint('toolflag', 'var3')
            print(var3)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config4.ini')
            var4 = config.getint('friendflag', 'var4')
            print(var4)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config5.ini')
            var5 = config.getint('reset', 'var5')
            print(var5)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config6.ini')
            var6 = config.getint('lizard', 'var6')
            print(var6)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config7.ini')
            var7 = config.getint('lizardext', 'var7')
            print(var7)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config8.ini')
            var8 = config.getint('okay', 'var8')
            print(var8)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config9.ini')
            var9 = config.getint('badend', 'var9')
            print(var9)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config10.ini')
            var10 = config.getint('badendext', 'var10')
            print(var10)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config11.ini')
            var11 = config.getint('splashskip', 'var11')
            print(var11)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config12.ini')
            var12 = config.getint('lizarddx', 'var12')
            print(var12)
            time.sleep(0.04)
            config = configparser.ConfigParser() #Verify config files are found and valid
            config.read('save/config.ini')
            var1 = config.getint('ch1endflag', 'var1')
            print(var1)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config2.ini')
            var2 = config.getint('chaptflagger', 'var2')
            print(var2)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config3.ini')
            var3 = config.getint('toolflag', 'var3')
            print(var3)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config4.ini')
            var4 = config.getint('friendflag', 'var4')
            print(var4)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config5.ini')
            var5 = config.getint('reset', 'var5')
            print(var5)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config6.ini')
            var6 = config.getint('lizard', 'var6')
            print(var6)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config7.ini')
            var7 = config.getint('lizardext', 'var7')
            print(var7)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config8.ini')
            var8 = config.getint('okay', 'var8')
            print(var8)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config9.ini')
            var9 = config.getint('badend', 'var9')
            print(var9)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config10.ini')
            var10 = config.getint('badendext', 'var10')
            print(var10)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config11.ini')
            var11 = config.getint('splashskip', 'var11')
            print(var11)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config12.ini')
            var12 = config.getint('lizarddx', 'var12')
            print(var12)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config13.ini')
            var13 = config.getint('splashskip2', 'var13')
            print(var13)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config14.ini')
            var14 = config.getint('gameover', 'var14')
            print(var14)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config15.ini')
            var15 = config.getint('blade', 'var15')
            print(var15)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config16.ini')
            var16 = config.getint('flower', 'var16')
            config = configparser.ConfigParser()
            config.read('save/config13.ini')
            var13 = config.getint('splashskip2', 'var13')
            print(var13)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config14.ini')
            var14 = config.getint('gameover', 'var14')
            print(var14)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config15.ini')
            var15 = config.getint('blade', 'var15')
            print(var15)
            time.sleep(0.04)
            config = configparser.ConfigParser()
            config.read('save/config16.ini')
            var16 = config.getint('flower', 'var16')
            config = configparser.ConfigParser()
            config.read('save/config16.ini')
            var16 = config.getint('flower', 'var16')
            print(var16)
            time.sleep(0.04)
            return
        except ValueError:
            pass

def versionHeader():
    print('\nThe Plains v0.22\n')
    return

def invDisplay():
    config = configparser.ConfigParser()
    config.read('save/config15.ini')
    var15 = config.getint('blade', 'var15')
    config = configparser.ConfigParser()
    config.read('save/config16.ini')
    var16 = config.getint('flower', 'var16')
    if var16 == 0:
        flower = "EMPTY"
    if var15 == 0:
        blade = "EMPTY"
    if var16 == 1:
        flower = "1x FLOWER"
    if var16 == 2 or var16 == 3:
        flower = "0x FLOWER"
    if var15 == 1:
        blade = "1x KNIFE"
    if var15 == 2:
        blade = "0x KNIFE"
    print("INV:", flower, blade, '\n', sep=" | ") #Inventory display
    return
